stages:
  - test
  - build
  - pages

variables:
  CARGO_HOME: "${CI_PROJECT_DIR}/.cargo"
  RUSTUP_HOME: "${CI_PROJECT_DIR}/.rustup"

default:
  image: rust:latest
  before_script:
    - rustup default stable
    - apt-get update -qq && apt-get install -y -qq clang btrfs-progs > /dev/null
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .cargo/registry
      - .cargo/git
      - target/

# -- Test stage ---------------------------------------------------------------

lint:
  stage: test
  script:
    - rustup toolchain install nightly --component rustfmt
    - cargo +nightly fmt --all --check
    - RUSTFLAGS="-D warnings" cargo check --all-targets

# -- Build stage --------------------------------------------------------------

build-x86:
  stage: build
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/btrfs
    expire_in: 1 week

build-x86-musl:
  stage: build
  script:
    - apt-get install -y -qq musl-tools > /dev/null
    - rustup target add x86_64-unknown-linux-musl
    - cargo build --release --target x86_64-unknown-linux-musl
  artifacts:
    paths:
      - target/x86_64-unknown-linux-musl/release/btrfs
    expire_in: 1 week

# -- Pages stage --------------------------------------------------------------

pages:
  stage: pages
  needs:
    - job: build-x86
      artifacts: true
    - job: build-x86-musl
      artifacts: true
  script:
    - mkdir -p public/binaries
    - cp target/release/btrfs public/binaries/btrfs-x86_64
    - cp target/x86_64-unknown-linux-musl/release/btrfs public/binaries/btrfs-x86_64-musl
  artifacts:
    paths:
      - public
