stages:
  - check
  - build
  - pages

check:
  image: nixos/nix:latest
  stage: check
  before_script:
    - echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf
  script:
    - nix flake check

build:
  image: nixos/nix:latest
  stage: build
  before_script:
    - echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf
  script:
    - nix build . -L
    - cp -r $(readlink result) public
  artifacts:
    paths:
      - public/
    expire_in: 1 week
  only:
    - master

pages:
  stage: pages
  image: alpine
  script:
    - apk add mdbook
    - mdbook build
    - mv target/book public
  artifacts:
    paths:
      - public
  only:
    - master
