exclude = ["target/**"]

[formatting]
align_entries = false
array_auto_collapse = true
array_auto_expand = true
array_trailing_comma = true
column_width = 80
compact_arrays = true
compact_inline_tables = false
indent_string = "  "
reorder_keys = false
trailing_newline = true
